### ISSUE TITLE
Clarify behaviour when using an INI file

### ISSUE THREAD

**Issue by 9600** [myriadrf/gr-limesdr#64]
See:

https://discourse.myriadrf.org/t/limesdr-usb-inconsistent-configuration-and-sample-rate/6345/3

Perhaps we could grey out all the other settings when an INI file is loaded?

**Comment by gracid** [comment]
I think the solution to this problem would be to just update documentation. Switching different block elements can get quite messy and annoying to work with.

**Comment by 9600** [comment]
Sure, sounds good and as long as the behaviour is clear.

**Comment by 9600** [comment]
I can see the notes in the Documentation tab, but I'm not sure that the behaviour is still sufficiently clear.

One option might be to move the File field to lower down on the General tab, so that it's set apart from the Serial and Channel etc. fields and not located in the middle of them. Then directly above or below the File field, place a warning to note that loading a file will override other settings.

**Comment by gracid** [comment]
Sadly, you cannot just place a warning note in middle of parameters or pretty much anywhere else in the block besides the documentation tab. I also think the location of File field is good because in order it goes: device identification(serial), File field (most important setting, overriding other ones), channel configuration (whether the block will need to use MIMO and which channel to use).

**Comment by gracid** [comment]
INI file load has been moved to advanced tab in 0b9a6d8c106f5bad4b7adc248b67382051e089a2.
